# Generated by Django 5.1.1 on 2024-11-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='analysis',
            new_name='resume',
        ),
    ]
