# Generated by Django 5.1.1 on 2024-11-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_service', '0002_profile_telephone_profile_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
