# Generated by Django 5.1.1 on 2024-11-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_service', '0003_alter_profile_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
