# Generated by Django 5.1.1 on 2024-11-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_service', '0004_alter_profile_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
