# Generated by Django 5.1.1 on 2024-10-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
