# Generated by Django 5.1.1 on 2024-11-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0002_alter_resume_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='ai_content_detection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='emotion_detection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='pii_and_anonymization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='sentiment_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
