# Generated by Django 5.1.1 on 2024-11-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0003_resumeanalysis_ai_content_detection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
