# Generated by Django 5.1.6 on 2025-02-20 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_jobs', models.TextField(blank=True, null=True)),
                ('improvement_tips', models.TextField(blank=True, null=True)),
                ('career_suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to='resumes.resumeanalysis')),
            ],
        ),
    ]
